name: stickity-stacks
version: '1.0'
summary: Frameless GTK4 sticky notes with stacking feature
description: |
  Stickity Stacks is a lightweight GTK4 Python application that provides
  frameless sticky notes with advanced stacking capabilities. Features include:
  - Frameless, borderless design
  - Note stacking with visual indicators
  - Customizable fonts and colors
  - Persistent storage
  - Drag-to-move functionality
  - Keyboard shortcuts (Ctrl+S for new note, Ctrl+D to delete)

base: core22
confinement: strict
grade: stable
license: GPL-3.0
website: https://github.com/Hot-snakes/stickity-stacks
source-code: https://github.com/Hot-snakes/stickity-stacks
issues: https://github.com/Hot-snakes/stickity-stacks/issues

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  stickity-stacks:
    command: bin/stickity_stacks.py
    desktop: usr/share/applications/com.stickity.stacks.desktop
    extensions: [gnome]
    plugs:
      - home
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - gsettings
      - unity7

parts:
  stickity-stacks:
    plugin: python
    source: .
    python-requirements:
      - PyGObject
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - gir1.2-gtk-4.0
      - gir1.2-gdk-4.0
      - gir1.2-pango-1.0
    organize:
      stickity_stacks.py: bin/stickity_stacks.py
    override-build: |
      craftctl default
      chmod +x $CRAFT_PART_INSTALL/bin/stickity_stacks.py
