name: stickity-stacks
version: '1.0'
summary: Frameless GTK4 sticky‐notes with stacking feature
description: |
  Stickity Stacks is a GTK4 Python app with note stacking, persistence,
  and customizable styling.
base: core22
confinement: strict
grade: stable

apps:
  stickity-stacks:
    command: bin/stickity-stacks
    desktop: usr/share/applications/com.stickity.stacks.desktop
    extensions: [gnome]
    plugs: [home, x11, wayland, gsettings]

parts:
  stickity-stacks:
    plugin: python
    python-packages: [.]
    source: .
    stage-packages:
      - python3-gi
      - gtk4
      - python3-pango
